<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>WOWSlider generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="WOW Slider, Carousel Script, Carousel Plugin" />
	<meta name="description" content="WOWSlider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" />
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
<body style="background-color:#d8d8d8">

	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="C:/wamp/www/MyPHP/data1/images/access.jpg" alt="access" title="access" id="wows1_0"/></li>
<li><a href="www.computerscience.com"><img src="C:/wamp/www/MyPHP/data1/images/accesslogo.jpg" alt="COMPUTER SCIENCE  DEPARTMENT" title="COMPUTER SCIENCE  DEPARTMENT" id="wows1_1"/></a> CSE </li>
<li><img src="C:/wamp/www/MyPHP/data1/images/com.jpg" alt="com" title="com" id="wows1_2"/></li>
<li><img src="C:/wamp/www/MyPHP/data1/images/cse1.jpg" alt="cse1" title="cse1" id="wows1_3"/></li>
<li><img src="C:/wamp/www/MyPHP/data1/images/cse2.jpg" alt="cse2" title="cse2" id="wows1_4"/></li>

<li><img src="C:/wamp/www/MyPHP/data1/images/cse3.jpg" alt="cse3" title="cse3" id="wows1_5"/></li>
<li><img src="C:/wamp/www/MyPHP/data1/images/cse4.jpg" alt="cse4" title="cse4" id="wows1_6"/></li>
</ul></div>
<div class="ws_bullets"><div>
<a href="#" title="access"><img src="C:/wamp/www/MyPHP/data1/tooltips/access.jpg" alt="access"/>1</a>
<a href="#" title="COMPUTER SCIENCE  DEPARTMENT"><img src="C:/wamp/www/MyPHP/data1/tooltips/accesslogo.jpg" alt="COMPUTER SCIENCE  DEPARTMENT"/>2</a>
<a href="#" title="com"><img src="C:/wamp/www/MyPHP/data1/tooltips/com.jpg" alt="com"/>3</a>
<a href="#" title="cse1"><img src="C:/wamp/www/MyPHP/data1/tooltips/cse1.jpg" alt="cse1"/>4</a>
<a href="#" title="cse2"><img src="C:/wamp/www/MyPHP/data1/tooltips/cse2.jpg" alt="cse2"/>5</a>
<a href="#" title="cse3"><img src="C:/wamp/www/MyPHP/data1/tooltips/cse3.jpg" alt="cse3"/>6</a>
<a href="#" title="cse4"><img src="C:/wamp/www/MyPHP/data1/tooltips/cse4.jpg" alt="cse4"/>7</a>
</div></div>
<span class="wsl"><a href="http://wowslider.com">Carousel Gallery</a> by WOWSlider.com v4.9</span>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="engine1/wowslider.js"></script>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>